### ISSUE TITLE
make on Ubuntu gives error.

### ISSUE THREAD

**Issue by eMonolith** [ianopolous/JPC#11]
warning: [options] bootstrap class path not set in conjunction with -source 6
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
make: *** [Makefile:34: build_core] Error 2

**Comment by eMonolith** [comment]
What version make are you running?

**Comment by ianopolous** [comment]
Thanks, that's fixed now.
