### ISSUE TITLE
Large difference with code from http://jpc.sourceforge.net, even though that page links here

### ISSUE THREAD

**Issue by toonvanacker** [ianopolous/JPC#7]
The code available for JPC on SourceForge seems more in line with the "Beautiful Architecture" article describing the project. Especially interesting there is the optimising compiler, which does not seem to be implemented in the project on GitHub.

Is there a reason for this huge difference in the two code bases? Does the project here on GitHub perform as well as the SourceForge project even though it only seems to do interpretation?

Sorry for making an issue here, I couldn't find a better place to ask this question. I am interested in emulating a different type of processor, and I'm wondering whether I should base myself on the GitHub or SourceForge source code.

**Comment by ianopolous** [comment]
The more advanced version on github is about 10x faster and much more accurate (can boot more operating systems). It's very carefully designed to make better use of modern processor architectures in particular branch prediction and code caches. I would definitely use this version for designing a different emulator.

**Comment by toonvanacker** [comment]
I'll do that, thank you very much for your quick reply.
